<a href="https://colab.research.google.com/github/jiteshpabla/PyTorch_tutorials/blob/master/UdacityPyTorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

## Single neuron

In [18]:
#creating random data
#set a set for random nums
torch.manual_seed(7)
#create a 1x5 matrix ie 1 row and 5 cols with standard normal distribution numbers
features = torch.randn((1, 5))


# initialize weights and bias
weights = torch.randn_like(features)
bias = torch.randn((1,1))

print(features)
print(weights)
print(bias)

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
tensor([[0.3177]])


In [19]:
#calc the output of a single layer using .sum()

#multiply
intermediates = torch.mul(features, weights)
print(intermediates)

#add
sums = torch.sum(intermediates) + bias
print(sums)

#activation
y = activation(sums)
print(y)

tensor([[ 0.1314, -0.2796,  1.1668, -0.1540, -2.8442]])
tensor([[-1.6619]])
tensor([[0.1595]])


In [23]:
'''
calc output using matrix
- matmul() - can return a matrix even is matrix sizes don't match for multiplication
- mm()
resize weights using
- reshape() - copies data, less efficient
- resize_() - inplace operation; can create data even if size is wrong
- view()
'''
activation(torch.mm(features, weights.view((5,1))) + bias)

tensor([[0.1595]])

## mutiple layers

In [31]:
class mlp_1_hidden:
    def __init__(self, n_input=3, n_hidden=2, n_output=1):
        self.n_input = n_input
        self.n_hidden = n_hidden
        self.n_output = n_output

    def calc_output(self, features):
        assert features.shape == (1, self.n_input)

        w1 = torch.randn((self.n_input, self.n_hidden))
        w2 = torch.randn((self.n_hidden, self.n_output))
        b1 = torch.randn((1, self.n_hidden))
        b2 = torch.randn((1, self.n_output))

        h1 = activation(torch.mm(features, w1) + b1)
        h2 = activation(torch.mm(h1, w2) + b2)

        return h2


n_input = 3
features = torch.randn((1, n_input))
mlp_model = mlp_1_hidden()
mlp_model.calc_output(features)

tensor([[0.7568]])

## torch to numpy and back

In [32]:
import numpy as np

In [41]:
a = np.random.rand(1,3)
a

array([[0.18551391, 0.47440679, 0.50597935]])

In [42]:
b = torch.from_numpy(a)
b

tensor([[0.1855, 0.4744, 0.5060]], dtype=torch.float64)

In [43]:
c = b.numpy()
c

array([[0.18551391, 0.47440679, 0.50597935]])

In [44]:
c[0][0] = 1.1
c

array([[1.1       , 0.47440679, 0.50597935]])

In [45]:
a

array([[1.1       , 0.47440679, 0.50597935]])

In [46]:
b

tensor([[1.1000, 0.4744, 0.5060]], dtype=torch.float64)

In [47]:
# the memory of numpy array and the tensor is shared